services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true 
      - WATCHPACK_POLLING=true 
      - FAST_REFRESH=false
      - WDS_SOCKET_PORT=3000
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}

    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    env_file:
      - ./.env

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=production
      - FIREBASE_SERVICE_ACCOUNT_KEY=${FIREBASE_SERVICE_ACCOUNT_KEY}
    env_file:
      - ./.env